### ISSUE TITLE
Robot Doesnt move

### ISSUE THREAD

**Issue by JeelChatrola** [prabinrath/armbot_nav#1]
I followed all the steps but the robot doesnt move , but i can see the tree being drawn on the rviz window
![image](https://user-images.githubusercontent.com/56308805/182826289-73f6c550-5c22-43ea-8cf2-86e25071862c.png)

**Comment by prabinrath** [comment]
@JeelChatrola this is a known issue with the rrt_exploration package. Please look at the changes in my [PR](https://github.com/hasauino/rrt_exploration/pull/27/commits/df1cd542f4de3d93df7a5e316b8a459a69284f71) to make rrt_exploration compatible with ROS Noetic.

**Comment by JeelChatrola** [comment]
Thank you it solved my problem.
